# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81fe6a99e6db9ed40fb344ce3e5b7b4541b180ab257ea1633178f154f4540fd3049fb9f65d4004b98cb9718e9e8f8246593e0908016f088dce7be1f4fe78d15f

test:
  secret_key_base: bd01b6b5af726e4779a0433adf202d994e8f0b6f2d386f1cb38935d85c1a45bb6a5a693f3682095dc99e537c6b081331c3131fc462a268b3fec5785bd8faf437

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
